#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

rm -v log.*

echo "rm -r processor*"
rm -r processor*
echo "rm -r 0.0*"
rm -r 0.0*
rm -r log.*.analyzed
rm -r postProcessing
cp -rv 0*.orig/ 0.000000
#runApplication decomposePar -latestTime
#echo "mpirun -np 2 $application -parallel > log.run1"
#valgrind --tool=memcheck --leak-check=yes  --track-origins=yes  --track-fds=yes mpirun -np 2 $application -parallel > log.run1
#valgrind --leak-check=yes --track-origins=yes --num-callers=30 mpirun -np 2 $application -parallel > log.run1
valgrind --track-origins=yes --num-callers=200 --leak-check=full --show-leak-kinds=all --track-fds=yes $application > log.run1
#--show-reachable=yes

runApplication reconstructPar -newTimes
rm -fv log.reconstructPar
#------------------------------------------------------------------------------
