#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`


runApplication decomposePar -latestTime
echo "mpirun -np 8 $application -parallel"
mpirun -np 8 $application -parallel > log.run1
runApplication reconstructPar -newTimes
rm -v log.reconstructPar
#------------------------------------------------------------------------------
