#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

echo "rm -r processor*"
rm -r processor*
runApplication decomposePar -latestTime
rm log.decomposePar

runParallel $application

runApplication reconstructPar -newTimes
rm log.reconstructPar
#------------------------------------------------------------------------------
